### ISSUE TITLE
hckgawi

### ISSUE THREAD

**Issue by donuts-are-good** [zpalmtree/dave#43]
![hecantkeepgettingawaywithit](https://user-images.githubusercontent.com/96031819/234148857-b2655dfc-2119-4e92-a8a0-e426637b2807.png)

**Comment by zpalmtree** [comment]
:thinking:

**Comment by donuts-are-good** [comment]
tried to msg you on matrix but no dice. your email still the same?

**Comment by zpalmtree** [comment]
Yeah, or you can use keybase. Email local part is `zp`

**Comment by donuts-are-good** [comment]
yeh i remember. its dnd night right now, ill email soon. give the lads my regards.
